import { CardSpecification, CardType } from './models';

export let baseDeck1: CardSpecification[] = [
    { id: "Baby Unicorn (Red)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Pink)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Orange)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Yellow)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Green)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Blue)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Purple)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Black)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (White)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Brown)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Rainbow)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Unicorn (Death)", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Baby Narwhal", type: CardType.BABY_UNICORN, amount: 1}, 
    { id: "Basic Unicorn (Red)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Orange)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Yellow)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Green)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Blue)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Indigo)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Basic Unicorn (Purple)", type: CardType.BASIC_UNICORN, amount: 3}, 
    { id: "Narwhal", type: CardType.BASIC_UNICORN, amount: 1}, 
    { id: "Rhinocorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Extremely Fertile Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Magical Kittencorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Stabby the Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Puppicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Rainbow Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Zombie Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Extremely Destructive Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Chainsaw Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Llamacorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Americorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Ginormous Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Seductive Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Angel Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Queen Bee Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Greedy Flying Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Annoying Flying Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Magical Flying Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Swift Flying Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Majestic Flying Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Unicorn Phoenix", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Unicorn on the Cob", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Black Knight Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Shark With a Horn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Shabby the Narwhal", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Narwhal Torpedo", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Alluring Narwhal", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Mermaid Unicorn", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Classy Narwhal", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "The Great Narwhal", type: CardType.MAGICAL_UNICORN, amount: 1}, 
    { id: "Unicorn Poison", type: CardType.MAGIC, amount: 3}, 
    { id: "Back Kick", type: CardType.MAGIC, amount: 3}, 
    { id: "Change of Luck", type: CardType.MAGIC, amount: 2}, 
    { id: "Glitter Tornado", type: CardType.MAGIC, amount: 2}, 
    { id: "Unicorn Swap", type: CardType.MAGIC, amount: 2}, 
    { id: "Re-Target", type: CardType.MAGIC, amount: 2}, 
    { id: "Unfair Bargain", type: CardType.MAGIC, amount: 2}, 
    { id: "Two-For-One", type: CardType.MAGIC, amount: 2}, 
    { id: "Unicorn Shrinkray", type: CardType.MAGIC, amount: 1}, 
    { id: "Targeted Destruction", type: CardType.MAGIC, amount: 1}, 
    { id: "Mystical Vortex", type: CardType.MAGIC, amount: 1}, 
    { id: "Good Deal", type: CardType.MAGIC, amount: 1}, 
    { id: "Shake Up", type: CardType.MAGIC, amount: 1}, 
    { id: "Blatant Thievery", type: CardType.MAGIC, amount: 1}, 
    { id: "Reset Button", type: CardType.MAGIC, amount: 1}, 
    { id: "Rainbow Mane", type: CardType.UPGRADE, amount: 3}, 
    { id: "Extra Tail", type: CardType.UPGRADE, amount: 3}, 
    { id: "Glitter Bomb", type: CardType.UPGRADE, amount: 2}, 
    { id: "Yay", type: CardType.UPGRADE, amount: 2}, 
    { id: "Unicorn Lasso", type: CardType.UPGRADE, amount: 1}, 
    { id: "Rainbow Aura", type: CardType.UPGRADE, amount: 1}, 
    { id: "Double Dutch", type: CardType.UPGRADE, amount: 1}, 
    { id: "Summoning Ritual", type: CardType.UPGRADE, amount: 1}, 
    { id: "Barbed Wire", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Pandamonium", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Sadistic Ritual", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Slowdown", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Nanny Cam", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Broken Stable", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Blinding Light", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Tiny Stable", type: CardType.DOWNGRADE, amount: 1}, 
    { id: "Neigh", type: CardType.INSTANT, amount: 14}, 
    { id: "Super Neigh", type: CardType.INSTANT, amount: 1}, 
];

export let gameStopDeck = { // Same as baseDeck1 but gamer instead of puppi

}